[package]
name = "cwmultisig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["derive"] }
cosmwasm-std = { workspace = true }
cw3-flex-multisig={workspace=true}
cw4-group = { path = "../../contracts/cw4-group", version = "2.0.0-rc.0" ,features = ["library"]}
cw4={workspace=true}
cw3={workspace=true}
cw20-base={workspace=true}
cw-utils={workspace=true}
